name: Opticon
options:
  bundleIdPrefix: com.heyitsmejosh
  deploymentTarget:
    iOS: "17.0"
settings:
  SWIFT_VERSION: "6.0"
  MARKETING_VERSION: "2.0.0"
  CURRENT_PROJECT_VERSION: "1"
targets:
  Opticon:
    type: application
    platform: iOS
    sources:
      - path: .
        excludes:
          - "*.xcodeproj"
          - "*.yml"
          - ".git"
          - ".gitignore"
          - "README.md"
          - "CLAUDE.md"
          - "architecture.svg"
          - Tests
    settings:
      INFOPLIST_FILE: Info.plist
      PRODUCT_BUNDLE_IDENTIFIER: com.heyitsmejosh.opticon
  OpticonTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Tests
    dependencies:
      - target: Opticon
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.heyitsmejosh.opticon.tests
